baseURL = 'https://agenco.de/'
languageCode = 'en-us'
title = 'Agenco'
theme = 'ananke'


DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Agenco"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.de]
    title = "Agenco De"
    weight = 2
    contentDir = "content/de"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "dark-grey"
  author = ""
  favicon = "favicon.ico"
  site_logo = "Agenco_Main_Logo_Transparent_bg.svg"
  description = "Agenco - Agents for Agility and Change"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "white"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/agencoEK"

